# WordPress database settings (shared)
wp_db_name: motorcade_wp
wp_db_user: motorcade_user

# Pulled from vault
wp_db_password: "{{ vault_wp_db_password }}"

# WordPress admin (used later by WP-CLI)
wp_admin_user: "{{ vault_wp_admin_user }}"
wp_admin_password: "{{ vault_wp_admin_password }}"
wp_admin_email: "{{ vault_wp_admin_email }}"

# WordPress site settings
wp_site_url: "{{ vault_wp_site_url }}"
wp_site_title: "{{ vault_wp_site_title }}"

#Texas DPS license Number
dps_license_number: "B31011701"

