$ANSIBLE_VAULT;1.1;AES256
65393036613930653938393135643731613533663665323433343633633732653939356239386164
3236306265623134363333633663336637323338646632630a653339396665653136366661323833
39363638353366313932653830333965363964313664356235343835613339323335623339326532
6138323964386339610a323332663332353362376538343636313265653630353134396436373463
36396133386265663364376130313035616561383466386535383739663366656264353737656432
63646633366136323063343465386530386436336435363061613833643163623562313266323165
66323064333536653038383239336139333764656332616633363063663932303932386531393139
65646438653862366261393364336330373333356636356436663664633263363262333636336164
30623763363166383161363236616435363766633666366162333533353931386266313365363431
33393836666438353631623637313764613561383861616363616532356534393662653936393764
65623064303836323037663236393235363630633136323033393639656338376237323438373732
65643563336339303962303535616631343566613130353737653334343064326361303436643465
39316336343662653030666164643131663566333533373139636138653235623361643731306433
32393135663939613562393366366631336364343762353536343661393938373134326233613033
63633163346137373634333066653830633534333733376563346436373031393766323937353039
65393164333134616131336639343336333830373766313134386462636462393063653736386466
33353233363634386235353235313439636363643839306438363633376463373863
