---
- name: Motorcade - install WP-CLI
  hosts: motorcade
  become: true

  tasks:
    - name: Download wp-cli.phar
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '0755'

    - name: Verify wp-cli is installed
      ansible.builtin.command: wp --info
      register: wpcli_info
      changed_when: false

    - name: Show wp-cli info
      ansible.builtin.debug:
        var: wpcli_info.stdout

